name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    env:
      working-directory: ./
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: report.tex
          working_directory: ./
      - uses: actions/upload-artifact@v2
        name: Upload artifact
        with:
          name: Report
          path: ./report.pdf
