name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    env:
      working-directory: ./
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile Practica1 document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: report1.tex
          working_directory: ./
      - name: Compile Practica2 document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: report2.tex
          working_directory: ./
      - uses: actions/upload-artifact@v2
        name: Upload artifact
        with:
          name: Report1
          path: ./report1.pdf
      - uses: actions/upload-artifact@v2
        name: Upload artifact
        with:
          name: Report2
          path: ./report2.pdf
